### ISSUE TITLE
Add dinamic data of LT_SETTINGS in FormContact

### ISSUE THREAD

**Issue by adminAgenciaServitec** [AgenciaServitec/landing-template#16]
- [x] Update config for form contact

![Screenshot 2024-06-26 at 12 56 36 AM](https://github.com/AgenciaServitec/landing-template/assets/104750139/0474927b-30d2-48ff-976d-618e8ef6dfff)

- [x]  Updated fetch to send mail with config data
![Screenshot 2024-06-26 at 12 58 19 AM](https://github.com/AgenciaServitec/landing-template/assets/104750139/ba276619-2473-44ce-b503-bbb62637f576)

**Comment by Ignacio2906** [comment]
![image](https://github.com/AgenciaServitec/landing-template/assets/145935490/15c17eff-1b25-4068-b80e-ca4e93a0f83f)
![Imagen de WhatsApp 2024-06-26 a las 13 25 45_a1d85da6](https://github.com/AgenciaServitec/landing-template/assets/145935490/154e64cc-0e48-4d34-8212-d66385e1fc6a)
