### ISSUE TITLE
Improve evaluacion light house

### ISSUE THREAD

**Issue by adminAgenciaServitec** [AgenciaServitec/landing-template#17]
- Performance
- SEO
- etc

**Comment by Ignacio2906** [comment]
![image](https://github.com/AgenciaServitec/landing-template/assets/145935490/2b5224d5-f587-4efe-a2db-3a898ba5676c)
 desktop

**Comment by Ignacio2906** [comment]
![Imagen de WhatsApp 2024-07-01 a las 18 24 55_3ffa092c](https://github.com/AgenciaServitec/landing-template/assets/145935490/33b84593-8185-4413-91f0-5cf044ac0676)

movile
