### ISSUE TITLE
Add data in the meta tags

### ISSUE THREAD

**Issue by adminAgenciaServitec** [AgenciaServitec/landing-template#18]
- [x] usar el campo keywords en su respectivo meta
- [x] usar el campo favicon en su respectivo meta

![Screenshot 2024-06-26 at 12 14 45 PM](https://github.com/AgenciaServitec/landing-template/assets/104750139/8c0f720f-b2e2-4920-a2c0-fc3a839e1423)

**Comment by Ignacio2906** [comment]
![image](https://github.com/AgenciaServitec/landing-template/assets/145935490/98edc0cd-c3f3-4141-a624-7b0fc85d6872)
